server:
  port: 8080
  contextPath: /
#  servlet:
#    context-path: /

spring:
  servlet:
    multipart.maxFileSize : 10240KB
    multipart.maxRequestSize: 102400KB
  datasource:
    username: root
    password: introcks1234
    url: jdbc:mysql://192.168.13.77:32000/moe?useUnicode=true&characterEncoding=utf8&useSSL=false
#    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*mapper.xml
  type-aliases-package: com.example.entity
#showSql
logging:
  level:
    com:
      example:
        mapper : debug

# dev环境下启用Swagger文档
springfox:
  documentation:
    enabled: true

# rabbitmq 配置
rabbitmq:
  mqtt:
    url: tcp://localhost:1883
    username: guest
    password: guest
    defaultTopic: testTopic