server:
  port: 8080
  contextPath: /
#  servlet:
#    context-path: /

spring:
  servlet:
    multipart.maxFileSize : 10240KB
    multipart.maxRequestSize: 102400KB
  redis:
    # Redis服务器连接端口
    port: 6379
    # Redis服务器地址
    host: 192.168.12.59
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接密码（默认为空）
    password: Intellifusion@20190108
    # 连接池最大连接数（使用负值表示没有限制）
    jedis.pool.max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    jedis.pool.max-wait: -1ms
    # 连接池中的最大空闲连接
    jedis.pool.max-idle: 8
    # 连接池中的最小空闲连接
    jedis.pool.min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 5000ms
  datasource:
#    username: root
#    password: introcks1234
#    url: jdbc:mysql://192.168.13.77:32000/moe?useUnicode=true&characterEncoding=utf8&useSSL=false
#    driver-class-name: com.mysql.jdbc.Driver
#   多数据源
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
            username: root
            password: introcks1234
            url: jdbc:mysql://192.168.13.77:32000/moe?useUnicode=true&characterEncoding=utf8&useSSL=false
#            driver-class-name: com.mysql.cj.jdbc.Driver
        test:
            username: root
            password: introcks1234
            url: jdbc:mysql://192.168.13.48:32000/moe?useUnicode=true&characterEncoding=utf8&useSSL=false
#            driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
#  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.gumo.demo.entity
#showSql
logging:
  level:
    com:
      example:
        mapper : debug

# dev环境下启用Swagger文档
springfox:
  documentation:
    enabled: true

# rabbitmq 配置
rabbitmq:
  mqtt:
    url: tcp://localhost:1883
    username: guest
    password: guest
    defaultTopic: testTopic