CREATE TABLE IF NOT EXISTS `t_device_info` (
    `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID  和基础服务的id一样',
    `model_id` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '型号类型（摄像头-0，测温面板—1）',
    `create_time` datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `device_name` varchar(64) NOT NULL COMMENT '设备名称',
    `creater` varchar(32) DEFAULT NULL COMMENT '创建人账号',
    `updater` varchar(32) DEFAULT NULL COMMENT '更新人',
    `delete_sign` tinyint unsigned NOT NULL COMMENT '是否删除（0-正常， 1-已删除）',
    `device_point` varchar(32) DEFAULT '0' COMMENT '设备坐标',
    `third_id` bigint unsigned NOT NULL COMMENT '基础服务Id（第三方Id）',
    `ip_address` varchar(30) DEFAULT NULL COMMENT 'ip地址',
    `address` varchar(60)  DEFAULT NULL COMMENT '设备地址',
    `place_label` varchar(30) DEFAULT NULL COMMENT '场所标签',
    `mac_address` varchar(50) DEFAULT NULL,
    `device_manage_id` int DEFAULT NULL,
    `rtsp` varchar(100)  DEFAULT NULL COMMENT 'rtsp流地址',
    `geo_string` varchar(30) DEFAULT NULL COMMENT '经纬度坐标串',
    `longitude` varchar(30) DEFAULT NULL COMMENT '经度',
    `latitude` varchar(30) DEFAULT NULL COMMENT '纬度',
    `login_name` varchar(30) DEFAULT NULL COMMENT '登录名',
    `login_password` varchar(30) DEFAULT NULL COMMENT '密码',
    `port` int DEFAULT NULL COMMENT '端口',
    `status` int DEFAULT '1' COMMENT '设备在离线状态：1：在线，0：离线  -1：未激活',
    `is_old` tinyint DEFAULT '0' COMMENT '是否利旧: 利旧-0 新增-1',
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE KEY `uidx_device_third_id` (`third_id`) USING BTREE COMMENT '第三方设备ID唯一'
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='设备表';